spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/informmerce
    username: rdijin
    password: '0918'

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE
