# 개발
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/informmerce
    username: rdijin
    password: '0918'

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ZLCeYh58ja9U1qlRHedu
            client-secret: u7JMoLR5WU
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
