spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ZLCeYh58ja9U1qlRHedu
            client-secret: u7JMoLR5WU
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            profile: name,email
            authorization-grant-type: authorization_code
            client-name: Naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
